# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/abdelrahman/data1/mywork/code/PycharmProjects/beamdicom/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1302, 649)
        MainWindow.setWindowTitle("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.studiesStackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.studiesStackedWidget.setObjectName("studiesStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.studiesBriefTableView = QtWidgets.QTableView(self.page)
        self.studiesBriefTableView.setStyleSheet("QTableView {\n"
"   outline: 0; /* Disable focus rect*/\n"
"}  \n"
"QTableView:item {\n"
"  border: 10px;\n"
"  padding: 20px;\n"
"}\n"
"QTableView::item:focus { /*Emulate focus*/\n"
"    color: black;\n"
"    background-color: rgb(155, 188, 242);\n"
"    border: 1px dashed black;\n"
"}")
        self.studiesBriefTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.studiesBriefTableView.setAlternatingRowColors(True)
        self.studiesBriefTableView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.studiesBriefTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.studiesBriefTableView.setIconSize(QtCore.QSize(256, 256))
        self.studiesBriefTableView.setShowGrid(False)
        self.studiesBriefTableView.setGridStyle(QtCore.Qt.NoPen)
        self.studiesBriefTableView.setObjectName("studiesBriefTableView")
        self.studiesBriefTableView.horizontalHeader().setVisible(False)
        self.studiesBriefTableView.horizontalHeader().setDefaultSectionSize(256)
        self.studiesBriefTableView.horizontalHeader().setStretchLastSection(True)
        self.studiesBriefTableView.verticalHeader().setDefaultSectionSize(256)
        self.studiesBriefTableView.verticalHeader().setMinimumSectionSize(256)
        self.gridLayout_4.addWidget(self.studiesBriefTableView, 0, 0, 1, 1)
        self.studiesStackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.studiesTableView = QtWidgets.QTableView(self.page_2)
        self.studiesTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.studiesTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.studiesTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.studiesTableView.setObjectName("studiesTableView")
        self.gridLayout_5.addWidget(self.studiesTableView, 0, 0, 1, 1)
        self.studiesStackedWidget.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.studiesStackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1302, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Tools = QtWidgets.QMenu(self.menuBar)
        self.menu_Tools.setObjectName("menu_Tools")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Settings = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Settings.setIcon(icon1)
        self.action_Settings.setObjectName("action_Settings")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon2)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/help_about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_About.setIcon(icon3)
        self.action_About.setObjectName("action_About")
        self.actionView_Images = QtWidgets.QAction(MainWindow)
        self.actionView_Images.setObjectName("actionView_Images")
        self.actionOpen_Images_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Images_Folder.setObjectName("actionOpen_Images_Folder")
        self.actionOpen_Study_Folder = QtWidgets.QAction(MainWindow)
        self.actionOpen_Study_Folder.setObjectName("actionOpen_Study_Folder")
        self.action_License = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/help_license.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/images/license.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_License.setIcon(icon4)
        self.action_License.setObjectName("action_License")
        self.action_Help = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Help.setIcon(icon5)
        self.action_Help.setObjectName("action_Help")
        self.actionTableView_Mode = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/tableview_48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTableView_Mode.setIcon(icon6)
        self.actionTableView_Mode.setObjectName("actionTableView_Mode")
        self.actionStudyViewMode = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/listview_48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStudyViewMode.setIcon(icon7)
        self.actionStudyViewMode.setObjectName("actionStudyViewMode")
        self.actionImport = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon8)
        self.actionImport.setObjectName("actionImport")
        self.actionShow_DicomRouter = QtWidgets.QAction(MainWindow)
        self.actionShow_DicomRouter.setCheckable(True)
        self.actionShow_DicomRouter.setChecked(True)
        self.actionShow_DicomRouter.setIcon(icon)
        self.actionShow_DicomRouter.setObjectName("actionShow_DicomRouter")
        self.action_Quit = QtWidgets.QAction(MainWindow)
        self.action_Quit.setIcon(icon2)
        self.action_Quit.setObjectName("action_Quit")
        self.actionDelete_Study_Folder = QtWidgets.QAction(MainWindow)
        self.actionDelete_Study_Folder.setObjectName("actionDelete_Study_Folder")
        self.rou_tes_ViewAction = QtWidgets.QAction(MainWindow)
        self.rou_tes_ViewAction.setCheckable(True)
        self.rou_tes_ViewAction.setIcon(icon8)
        self.rou_tes_ViewAction.setObjectName("rou_tes_ViewAction")
        self.menu_File.addAction(self.action_Exit)
        self.menu_Help.addAction(self.action_About)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Tools.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.action_About)
        self.toolBar.addAction(self.action_License)
        self.toolBar.addAction(self.rou_tes_ViewAction)
        self.toolBar.addAction(self.action_Help)
        self.toolBar.addAction(self.action_Settings)
        self.toolBar.addAction(self.action_Exit)

        self.retranslateUi(MainWindow)
        self.studiesStackedWidget.setCurrentIndex(0)
        self.actionShow_DicomRouter.toggled['bool'].connect(MainWindow.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_Settings.setText(_translate("MainWindow", "&Settings"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.actionView_Images.setText(_translate("MainWindow", "View Images"))
        self.actionOpen_Images_Folder.setText(_translate("MainWindow", "Open Images Folder"))
        self.actionOpen_Study_Folder.setText(_translate("MainWindow", "Open Study Folder"))
        self.action_License.setText(_translate("MainWindow", "License"))
        self.action_Help.setText(_translate("MainWindow", "Help"))
        self.actionTableView_Mode.setText(_translate("MainWindow", "Table View"))
        self.actionTableView_Mode.setToolTip(_translate("MainWindow", "Table View"))
        self.actionStudyViewMode.setText(_translate("MainWindow", "Study View Mode"))
        self.actionStudyViewMode.setToolTip(_translate("MainWindow", "Study View Mode"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionShow_DicomRouter.setText(_translate("MainWindow", "Show DicomRouter"))
        self.action_Quit.setText(_translate("MainWindow", "Quit"))
        self.action_Quit.setToolTip(_translate("MainWindow", "Quit"))
        self.actionDelete_Study_Folder.setText(_translate("MainWindow", "Delete Study"))
        self.rou_tes_ViewAction.setText(_translate("MainWindow", "Rou&tes View"))


import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
