# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/melnaquib/work/client/reportly/code/beamdicom/ui/SettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1249, 935)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.dicomServerTab = QtWidgets.QWidget()
        self.dicomServerTab.setObjectName("dicomServerTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dicomServerTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dicomServerWidget = DicomNetworkSettingWidget(self.dicomServerTab)
        self.dicomServerWidget.setObjectName("dicomServerWidget")
        self.gridLayout_2.addWidget(self.dicomServerWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dicomServerTab, "")
        self.dicomSenderTab = QtWidgets.QWidget()
        self.dicomSenderTab.setObjectName("dicomSenderTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dicomSenderTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dicomSenderWidget = DicomNetworkSettingWidget(self.dicomSenderTab)
        self.dicomSenderWidget.setObjectName("dicomSenderWidget")
        self.gridLayout_3.addWidget(self.dicomSenderWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dicomSenderTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.targetPacsWidget = DicomNetworkSettingWidget(self.tab)
        self.targetPacsWidget.setObjectName("targetPacsWidget")
        self.gridLayout_5.addWidget(self.targetPacsWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.directoriesTab = QtWidgets.QWidget()
        self.directoriesTab.setObjectName("directoriesTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.directoriesTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.directoriesTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.directoriesTab)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.storageFldrBtn = QtWidgets.QPushButton(self.directoriesTab)
        self.storageFldrBtn.setObjectName("storageFldrBtn")
        self.gridLayout_4.addWidget(self.storageFldrBtn, 3, 3, 1, 1)
        self.logFldrBtn = QtWidgets.QPushButton(self.directoriesTab)
        self.logFldrBtn.setObjectName("logFldrBtn")
        self.gridLayout_4.addWidget(self.logFldrBtn, 1, 3, 1, 1)
        self.logFldrLineUnit = QtWidgets.QLineEdit(self.directoriesTab)
        self.logFldrLineUnit.setObjectName("logFldrLineUnit")
        self.gridLayout_4.addWidget(self.logFldrLineUnit, 1, 2, 1, 1)
        self.runFldrbtn = QtWidgets.QPushButton(self.directoriesTab)
        self.runFldrbtn.setObjectName("runFldrbtn")
        self.gridLayout_4.addWidget(self.runFldrbtn, 0, 3, 1, 1)
        self.runFdrLineUnit = QtWidgets.QLineEdit(self.directoriesTab)
        self.runFdrLineUnit.setObjectName("runFdrLineUnit")
        self.gridLayout_4.addWidget(self.runFdrLineUnit, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.directoriesTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.directoriesTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 0, 1, 1)
        self.storageFldrLineUnit = QtWidgets.QLineEdit(self.directoriesTab)
        self.storageFldrLineUnit.setObjectName("storageFldrLineUnit")
        self.gridLayout_4.addWidget(self.storageFldrLineUnit, 3, 2, 1, 1)
        self.tmpFldrLineUnit = QtWidgets.QLineEdit(self.directoriesTab)
        self.tmpFldrLineUnit.setObjectName("tmpFldrLineUnit")
        self.gridLayout_4.addWidget(self.tmpFldrLineUnit, 2, 2, 1, 1)
        self.tmpFldrBtn = QtWidgets.QPushButton(self.directoriesTab)
        self.tmpFldrBtn.setObjectName("tmpFldrBtn")
        self.gridLayout_4.addWidget(self.tmpFldrBtn, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.directoriesTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.directoriesTab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 4, 2, 1, 2)
        self.tabWidget.addTab(self.directoriesTab, "")
        self.ConversionTab = QtWidgets.QWidget()
        self.ConversionTab.setObjectName("ConversionTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ConversionTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.ConversionTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.cnvFmtComboBox = QtWidgets.QComboBox(self.ConversionTab)
        self.cnvFmtComboBox.setObjectName("cnvFmtComboBox")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.gridLayout_6.addWidget(self.cnvFmtComboBox, 1, 1, 1, 1)
        self.cnvDirBrowsePushButton = QtWidgets.QPushButton(self.ConversionTab)
        self.cnvDirBrowsePushButton.setObjectName("cnvDirBrowsePushButton")
        self.gridLayout_6.addWidget(self.cnvDirBrowsePushButton, 0, 0, 1, 1)
        self.cnvDirLineEdit = QtWidgets.QLineEdit(self.ConversionTab)
        self.cnvDirLineEdit.setObjectName("cnvDirLineEdit")
        self.gridLayout_6.addWidget(self.cnvDirLineEdit, 0, 1, 1, 1)
        self.tabWidget.addTab(self.ConversionTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dicomServerTab), _translate("Form", "Dicom Server"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dicomSenderTab), _translate("Form", "Dicom Sender"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Target Pacs"))
        self.label_4.setText(_translate("Form", "Temp Folder"))
        self.label.setText(_translate("Form", "Run Folder"))
        self.storageFldrBtn.setText(_translate("Form", "......"))
        self.logFldrBtn.setText(_translate("Form", "......."))
        self.runFldrbtn.setText(_translate("Form", "....."))
        self.label_2.setText(_translate("Form", "Log Folder"))
        self.label_3.setText(_translate("Form", "Storage Folder"))
        self.tmpFldrBtn.setText(_translate("Form", "......."))
        self.label_6.setText(_translate("Form", "Case Folder Name"))
        self.comboBox.setItemText(0, _translate("Form", "Last Name"))
        self.comboBox.setItemText(1, _translate("Form", "Patient ID"))
        self.comboBox.setItemText(2, _translate("Form", "Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.directoriesTab), _translate("Form", "Directories"))
        self.label_5.setText(_translate("Form", "Format"))
        self.cnvFmtComboBox.setItemText(0, _translate("Form", "png"))
        self.cnvFmtComboBox.setItemText(1, _translate("Form", "jpg"))
        self.cnvFmtComboBox.setItemText(2, _translate("Form", "bmp"))
        self.cnvFmtComboBox.setItemText(3, _translate("Form", "pdf"))
        self.cnvDirBrowsePushButton.setText(_translate("Form", "Browse..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ConversionTab), _translate("Form", "Conversion"))

from mtbm.uiDicomNetworkSettingWidget import DicomNetworkSettingWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

