# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/melnaquib/work/client/reportly/code/beamdicom/ui/SettingWidgetNew.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(973, 744)
        Form.setMinimumSize(QtCore.QSize(900, 600))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setMinimumSize(QtCore.QSize(900, 600))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 953, 724))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.targerpacs2groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.targerpacs2groupBox.setObjectName("targerpacs2groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.targerpacs2groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.targetPacs1Widget = DicomNetworkSettingWidget(self.targerpacs2groupBox)
        self.targetPacs1Widget.setObjectName("targetPacs1Widget")
        self.gridLayout_4.addWidget(self.targetPacs1Widget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.targerpacs2groupBox, 1, 1, 1, 1)
        self.directoriesgroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.directoriesgroupBox.setObjectName("directoriesgroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.directoriesgroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.storageFldrBtn = QtWidgets.QPushButton(self.directoriesgroupBox)
        self.storageFldrBtn.setObjectName("storageFldrBtn")
        self.gridLayout_2.addWidget(self.storageFldrBtn, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.runFdrLineUnit = QtWidgets.QLineEdit(self.directoriesgroupBox)
        self.runFdrLineUnit.setObjectName("runFdrLineUnit")
        self.gridLayout_2.addWidget(self.runFdrLineUnit, 0, 1, 1, 1)
        self.logFldrBtn = QtWidgets.QPushButton(self.directoriesgroupBox)
        self.logFldrBtn.setObjectName("logFldrBtn")
        self.gridLayout_2.addWidget(self.logFldrBtn, 1, 2, 1, 1)
        self.runFldrbtn = QtWidgets.QPushButton(self.directoriesgroupBox)
        self.runFldrbtn.setObjectName("runFldrbtn")
        self.gridLayout_2.addWidget(self.runFldrbtn, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.directoriesgroupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 4, 1, 1, 2)
        self.tmpFldrLineUnit = QtWidgets.QLineEdit(self.directoriesgroupBox)
        self.tmpFldrLineUnit.setObjectName("tmpFldrLineUnit")
        self.gridLayout_2.addWidget(self.tmpFldrLineUnit, 2, 1, 1, 1)
        self.logFldrLineUnit = QtWidgets.QLineEdit(self.directoriesgroupBox)
        self.logFldrLineUnit.setObjectName("logFldrLineUnit")
        self.gridLayout_2.addWidget(self.logFldrLineUnit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.tmpFldrBtn = QtWidgets.QPushButton(self.directoriesgroupBox)
        self.tmpFldrBtn.setObjectName("tmpFldrBtn")
        self.gridLayout_2.addWidget(self.tmpFldrBtn, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.storageFldrLineUnit = QtWidgets.QLineEdit(self.directoriesgroupBox)
        self.storageFldrLineUnit.setObjectName("storageFldrLineUnit")
        self.gridLayout_2.addWidget(self.storageFldrLineUnit, 3, 1, 1, 1)
        self.gridLayout_8.addWidget(self.directoriesgroupBox, 2, 0, 1, 1)
        self.targetpacsgroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.targetpacsgroupBox.setObjectName("targetpacsgroupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.targetpacsgroupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.targetPacsWidget = DicomNetworkSettingWidget(self.targetpacsgroupBox)
        self.targetPacsWidget.setObjectName("targetPacsWidget")
        self.gridLayout_7.addWidget(self.targetPacsWidget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.targetpacsgroupBox, 1, 0, 1, 1)
        self.dicomservergroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.dicomservergroupBox.setObjectName("dicomservergroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.dicomservergroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dicomServerWidget = DicomNetworkSettingWidget(self.dicomservergroupBox)
        self.dicomServerWidget.setObjectName("dicomServerWidget")
        self.gridLayout_5.addWidget(self.dicomServerWidget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.dicomservergroupBox, 0, 0, 1, 1)
        self.conversiongroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.conversiongroupBox.setObjectName("conversiongroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.conversiongroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cnvDirBrowsePushButton = QtWidgets.QPushButton(self.conversiongroupBox)
        self.cnvDirBrowsePushButton.setObjectName("cnvDirBrowsePushButton")
        self.gridLayout_3.addWidget(self.cnvDirBrowsePushButton, 0, 0, 1, 1)
        self.cnvDirLineEdit = QtWidgets.QLineEdit(self.conversiongroupBox)
        self.cnvDirLineEdit.setObjectName("cnvDirLineEdit")
        self.gridLayout_3.addWidget(self.cnvDirLineEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.conversiongroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.cnvFmtComboBox = QtWidgets.QComboBox(self.conversiongroupBox)
        self.cnvFmtComboBox.setObjectName("cnvFmtComboBox")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.gridLayout_3.addWidget(self.cnvFmtComboBox, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.conversiongroupBox, 2, 1, 1, 1)
        self.dicomsendergroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.dicomsendergroupBox.setObjectName("dicomsendergroupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dicomsendergroupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.dicomSenderWidget = DicomNetworkSettingWidget(self.dicomsendergroupBox)
        self.dicomSenderWidget.setObjectName("dicomSenderWidget")
        self.gridLayout_6.addWidget(self.dicomSenderWidget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.dicomsendergroupBox, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.targerpacs2groupBox.setTitle(_translate("Form", "Target Pacs 2"))
        self.directoriesgroupBox.setTitle(_translate("Form", "Directories"))
        self.storageFldrBtn.setText(_translate("Form", "......"))
        self.label_6.setText(_translate("Form", "Case Folder Name"))
        self.label_3.setText(_translate("Form", "Storage Folder"))
        self.logFldrBtn.setText(_translate("Form", "......."))
        self.runFldrbtn.setText(_translate("Form", "....."))
        self.label.setText(_translate("Form", "Run Folder"))
        self.comboBox.setItemText(0, _translate("Form", "Last Name"))
        self.comboBox.setItemText(1, _translate("Form", "Patient ID"))
        self.comboBox.setItemText(2, _translate("Form", "Date"))
        self.label_2.setText(_translate("Form", "Log Folder"))
        self.tmpFldrBtn.setText(_translate("Form", "......."))
        self.label_4.setText(_translate("Form", "Temp Folder"))
        self.targetpacsgroupBox.setTitle(_translate("Form", "Target Pacs"))
        self.dicomservergroupBox.setTitle(_translate("Form", "Dicom Server"))
        self.conversiongroupBox.setTitle(_translate("Form", "Conversion"))
        self.cnvDirBrowsePushButton.setText(_translate("Form", "Browse..."))
        self.label_5.setText(_translate("Form", "Format"))
        self.cnvFmtComboBox.setItemText(0, _translate("Form", "png"))
        self.cnvFmtComboBox.setItemText(1, _translate("Form", "jpg"))
        self.cnvFmtComboBox.setItemText(2, _translate("Form", "bmp"))
        self.cnvFmtComboBox.setItemText(3, _translate("Form", "pdf"))
        self.dicomsendergroupBox.setTitle(_translate("Form", "Dicom Sender"))

from DicomNetworkSettingWidget import DicomNetworkSettingWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

