# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/melnaquib/work/client/reportly/code/beamdicom/ui/SettingWidgetIpR.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(624, 298)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.conversiongroupBox = QtWidgets.QGroupBox(Form)
        self.conversiongroupBox.setObjectName("conversiongroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.conversiongroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cnvFmtComboBox = QtWidgets.QComboBox(self.conversiongroupBox)
        self.cnvFmtComboBox.setObjectName("cnvFmtComboBox")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.cnvFmtComboBox.addItem("")
        self.gridLayout_3.addWidget(self.cnvFmtComboBox, 1, 1, 1, 1)
        self.cnvDirLineEdit = QtWidgets.QLineEdit(self.conversiongroupBox)
        self.cnvDirLineEdit.setObjectName("cnvDirLineEdit")
        self.gridLayout_3.addWidget(self.cnvDirLineEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.conversiongroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.cnvDirBrowsePushButton = QtWidgets.QPushButton(self.conversiongroupBox)
        self.cnvDirBrowsePushButton.setObjectName("cnvDirBrowsePushButton")
        self.gridLayout_3.addWidget(self.cnvDirBrowsePushButton, 0, 0, 1, 1)
        self.removeDicomCheckBox = QtWidgets.QCheckBox(self.conversiongroupBox)
        self.removeDicomCheckBox.setObjectName("removeDicomCheckBox")
        self.gridLayout_3.addWidget(self.removeDicomCheckBox, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.conversiongroupBox, 0, 1, 1, 2)
        self.directoriesgroupBox = QtWidgets.QGroupBox(Form)
        self.directoriesgroupBox.setObjectName("directoriesgroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.directoriesgroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.logFldrBtn = QtWidgets.QPushButton(self.directoriesgroupBox)
        self.logFldrBtn.setObjectName("logFldrBtn")
        self.gridLayout_2.addWidget(self.logFldrBtn, 1, 2, 1, 1)
        self.runFdrLineUnit = QtWidgets.QLineEdit(self.directoriesgroupBox)
        self.runFdrLineUnit.setObjectName("runFdrLineUnit")
        self.gridLayout_2.addWidget(self.runFdrLineUnit, 0, 1, 1, 1)
        self.logFldrLineUnit = QtWidgets.QLineEdit(self.directoriesgroupBox)
        self.logFldrLineUnit.setObjectName("logFldrLineUnit")
        self.gridLayout_2.addWidget(self.logFldrLineUnit, 1, 1, 1, 1)
        self.runFldrbtn = QtWidgets.QPushButton(self.directoriesgroupBox)
        self.runFldrbtn.setObjectName("runFldrbtn")
        self.gridLayout_2.addWidget(self.runFldrbtn, 0, 2, 1, 1)
        self.tmpFldrLineUnit = QtWidgets.QLineEdit(self.directoriesgroupBox)
        self.tmpFldrLineUnit.setObjectName("tmpFldrLineUnit")
        self.gridLayout_2.addWidget(self.tmpFldrLineUnit, 2, 1, 1, 1)
        self.tmpFldrBtn = QtWidgets.QPushButton(self.directoriesgroupBox)
        self.tmpFldrBtn.setObjectName("tmpFldrBtn")
        self.gridLayout_2.addWidget(self.tmpFldrBtn, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.directoriesgroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.storageFldrLineUnit = QtWidgets.QLineEdit(self.directoriesgroupBox)
        self.storageFldrLineUnit.setObjectName("storageFldrLineUnit")
        self.gridLayout_2.addWidget(self.storageFldrLineUnit, 3, 1, 1, 1)
        self.storageFldrBtn = QtWidgets.QPushButton(self.directoriesgroupBox)
        self.storageFldrBtn.setObjectName("storageFldrBtn")
        self.gridLayout_2.addWidget(self.storageFldrBtn, 3, 2, 1, 1)
        self.foldernamemodFld = QtWidgets.QComboBox(self.directoriesgroupBox)
        self.foldernamemodFld.setObjectName("foldernamemodFld")
        self.foldernamemodFld.addItem("")
        self.foldernamemodFld.addItem("")
        self.foldernamemodFld.addItem("")
        self.gridLayout_2.addWidget(self.foldernamemodFld, 4, 1, 1, 2)
        self.gridLayout.addWidget(self.directoriesgroupBox, 1, 0, 2, 2)
        self.dicomservergroupBox = QtWidgets.QGroupBox(Form)
        self.dicomservergroupBox.setObjectName("dicomservergroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dicomservergroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dicomServerWidget = DicomNetworkSettingWidget(self.dicomservergroupBox)
        self.dicomServerWidget.setObjectName("dicomServerWidget")
        self.gridLayout_4.addWidget(self.dicomServerWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.dicomservergroupBox, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ipAddressFld = QtWidgets.QLineEdit(self.groupBox)
        self.ipAddressFld.setReadOnly(True)
        self.ipAddressFld.setObjectName("ipAddressFld")
        self.gridLayout_9.addWidget(self.ipAddressFld, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.conversiongroupBox.setTitle(_translate("Form", "Conversion"))
        self.cnvFmtComboBox.setItemText(0, _translate("Form", "png"))
        self.cnvFmtComboBox.setItemText(1, _translate("Form", "jpg"))
        self.cnvFmtComboBox.setItemText(2, _translate("Form", "bmp"))
        self.cnvFmtComboBox.setItemText(3, _translate("Form", "pdf"))
        self.label_5.setText(_translate("Form", "Format"))
        self.cnvDirBrowsePushButton.setText(_translate("Form", "Browse..."))
        self.removeDicomCheckBox.setText(_translate("Form", "Remove Dicom After Conversion"))
        self.directoriesgroupBox.setTitle(_translate("Form", "Directories"))
        self.label.setText(_translate("Form", "Run Folder"))
        self.label_2.setText(_translate("Form", "Log Folder"))
        self.label_4.setText(_translate("Form", "Temp Folder"))
        self.logFldrBtn.setText(_translate("Form", "......."))
        self.runFldrbtn.setText(_translate("Form", "....."))
        self.tmpFldrBtn.setText(_translate("Form", "......."))
        self.label_3.setText(_translate("Form", "Storage Folder"))
        self.label_6.setText(_translate("Form", "Case Folder Name"))
        self.storageFldrBtn.setText(_translate("Form", "......"))
        self.foldernamemodFld.setItemText(0, _translate("Form", "Patient Name"))
        self.foldernamemodFld.setItemText(1, _translate("Form", "Patient ID"))
        self.foldernamemodFld.setItemText(2, _translate("Form", "Study IUID"))
        self.dicomservergroupBox.setTitle(_translate("Form", "Dicom Server"))
        self.groupBox.setTitle(_translate("Form", "Network"))
        self.label_7.setText(_translate("Form", "Ip Address"))

from DicomNetworkSettingWidget import DicomNetworkSettingWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

